name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create Draft
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: true
